version: "3.7"

services:
  db:
    image: postgres:12.7
    restart: on-failure
    environment:
      POSTGRES_USER: tmori
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"    
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
